# .goreleaser.yml
# Build customization
builds:
  - binary: terraform-provider-citrixadc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
